// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPythonScripts() {
  return window['go']['main']['App']['CheckPythonScripts']();
}

export function CheckStorageJSON() {
  return window['go']['main']['App']['CheckStorageJSON']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitPythonVenv() {
  return window['go']['main']['App']['InitPythonVenv']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SetupApp(arg1) {
  return window['go']['main']['App']['SetupApp'](arg1);
}

export function SetupLogger(arg1) {
  return window['go']['main']['App']['SetupLogger'](arg1);
}
