// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CheckInitStatus():Promise<string>;

export function GetFilesFromStorage():Promise<any>;

export function OpenLog():Promise<void>;

export function OpenStorage():Promise<void>;

export function ReadFileFromStorage(arg1:string):Promise<string>;

export function SaveFileToStorage(arg1:string,arg2:string):Promise<void>;

export function SetupApp(arg1:context.Context):Promise<void>;

export function StartInit():Promise<void>;
