// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CheckPythonScripts():Promise<void>;

export function CheckStorageJSON():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function InitPythonVenv():Promise<void>;

export function LoadConfig():Promise<void>;

export function SetupApp(arg1:context.Context):Promise<void>;

export function SetupLogger(arg1:string):Promise<void>;
