// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CheckInitStatus():Promise<string>;

export function OpenLog():Promise<void>;

export function OpenStorage():Promise<void>;

export function SetupApp(arg1:context.Context):Promise<void>;

export function StartInit():Promise<void>;
