// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInitStatus() {
  return window['go']['main']['App']['CheckInitStatus']();
}

export function OpenLog() {
  return window['go']['main']['App']['OpenLog']();
}

export function OpenStorage() {
  return window['go']['main']['App']['OpenStorage']();
}

export function SetupApp(arg1) {
  return window['go']['main']['App']['SetupApp'](arg1);
}

export function StartInit() {
  return window['go']['main']['App']['StartInit']();
}
