// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInitStatus() {
  return window['go']['main']['App']['CheckInitStatus']();
}

export function CleanLog() {
  return window['go']['main']['App']['CleanLog']();
}

export function DeleteFileFromStorage(arg1) {
  return window['go']['main']['App']['DeleteFileFromStorage'](arg1);
}

export function GetFilesFromStorage() {
  return window['go']['main']['App']['GetFilesFromStorage']();
}

export function OpenLog() {
  return window['go']['main']['App']['OpenLog']();
}

export function OpenStorage() {
  return window['go']['main']['App']['OpenStorage']();
}

export function ReadFileFromStorage(arg1) {
  return window['go']['main']['App']['ReadFileFromStorage'](arg1);
}

export function SaveFileToStorage(arg1, arg2) {
  return window['go']['main']['App']['SaveFileToStorage'](arg1, arg2);
}

export function SetupApp(arg1) {
  return window['go']['main']['App']['SetupApp'](arg1);
}

export function StartInit() {
  return window['go']['main']['App']['StartInit']();
}
